data_sources:
  tickers: ["SPY"]
  macro_indicators: ["^VIX", "^MOVE", "^VVIX"]
  days_back: 180
  intraday_interval: "15/minute"
  end_date: !now
  itm-otm: .05
  poly_api: UvSnRxq0stT5Lb9p2rvGO6JBFzzBuclX
  exp_threshold: 30